apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: ezee/argocd
  newName: ezee/argocd
  newTag: v2.0.3
resources:
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis
